### ISSUE TITLE
"Import qt" or "import Qt"?

### ISSUE THREAD

**Issue by mottosso** [mottosso/Qt#1]
PEP08 mandates lower-case module names. But Qt bindings are traditionally mixedcase.

```python
from qt import QtWidgets

# Or

from Qt import QtWidgets
```

**Comment by mottosso** [comment]
I think uppercase might be more familiar. @fredrikaverpil?

**Comment by fredrikaverpil** [comment]
I'm a big fan of PEP. So this makes me a bit torn in-between the two choices.

This arguably looks better:

    from Qt import QtWidgets

...than this:

    from qt import QtWidgets

I guess maybe that's what's most important.

**Comment by mottosso** [comment]
Yeah, me as well. It's a tough one.

Let's try uppercase until we run into trouble.
