### ISSUE TITLE
Error when no Qt binding is installed

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt#10]
There should be some kind of error when there's no Qt binding available for loading.

**Comment by fredrikaverpil** [comment]
Oh, crap. It's already in there.

**Comment by mottosso** [comment]
Yeah, it's a message to stderr, but it's worth discussing what kind of error it should produce.

In ordinary circumstances, an unavailable module would throw an `ImportError`. Maybe this should too?

**Comment by fredrikaverpil** [comment]
Possibly, yes. We should be more specific on what we tried to do and what caused an error.

**Comment by fredrikaverpil** [comment]
I think we should use `raise ImportError` instead:

    raise ImportError("Could not find appropriate bindings for Qt")

```python
>>> try:
...     import Qt
... except ImportError:
...     print 'oh no'
...
oh no
```
