### ISSUE TITLE
Why the <br> in README?

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt#14]
I noticed the README has a bunch of `<br>` tags which makes it really long (vertically). Just wondering if you intended to do that or if it was in error. The page becomes really long on a laptop but perhaps you felt readability was improved...?

**Comment by mottosso** [comment]
It's subjective I agree, but I'd prefer to keep them in.

I'm expecting the README to get busy, and they help break apart relevant sections and prevent it looking like a wall of text.

Here's a more mature article where I think they make good use.
- https://github.com/pyblish/pyblish/wiki

If you still think they won't make good use, I'm ok removing them. No biggie.

**Comment by fredrikaverpil** [comment]
Good point, ok. :)
