### ISSUE TITLE
sys.modules["Qt"] breaks sys

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt#15]
For some reason, when you set e.g. `sys.modules['Qt'] = PyQt5`, the `sys` module cannot be used after this:

```python
load_pyqt5()
print sys
>>> None
```

I was expecting:

```python
load_pyqt5()
print sys
>>> <module 'sys' (built-in)>
```

**Comment by fredrikaverpil** [comment]
Okay, so I'm still not sure exactly why this happens, but if you re-import `sys` outside of the load functions, it'll be available again.

**Comment by fredrikaverpil** [comment]
So it seems that when since the file is called `Qt.py` and we are doing `sys.modules['Qt']`, the latter removes the reference to the former when you `import Qt`. When there are no longer any reference to a module, it will drop all its globals by replacing them with `None`.

If the filename isn't the same as the module name `Qt`, we wouldn't see this happening.

So, it's not a bug. But I question the design of this. What do you think, @mottosso?

**Comment by mottosso** [comment]
Ah, that makes sense. Nice find.

Well, we don't have to use the `sys.modules["Qt"]` trick when we use an individual module like this. I only used that in Pyblish Lite because I *didn't* have an individual module.

You could simply do.

```python
from PySide2 import QtWidgets
```

And `QtWidgets` would be accessible via import.

**Comment by fredrikaverpil** [comment]
What's funny is that with the current approach, we don't expose the functions or e.g. the `sys` module because of dropped globals:

	>>> import Qt
	>>> dir(Qt)
	['Enginio', 'Qt', 'QtBluetooth', 'QtCore', 'QtDesigner', 'QtGui', 'QtHelp', 'QtLocation', 'QtMacExtras', 'QtMultimedia', 'QtMultimediaWidgets', 'QtNetwork', 'QtNfc', 'QtOpenGL', 'QtPositioning', 'QtPrintSupport', 'QtQml', 'QtQuick', 'QtQuickWidgets', 'QtSensors', 'QtSerialPort', 'QtSql', 'QtSvg', 'QtWebChannel', 'QtWebEngineWidgets', 'QtWebSockets', 'QtWidgets', 'QtXml', 'QtXmlPatterns', '__binding__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__']

If we were to "fix" that, we'd instead see all those functions etc:

	>>> import Qt
	>>> dir(Qt)
	['PyQt5', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '_load_pyqt4', '_load_pyqt5', '_load_pyside', '_load_pyside2', 'sys']

So, in a way, it could be quite useful to clean house and do the `sys.modules['Qt']` thing after all. But perhaps we should do that as the very last thing, rather than doing it in the middle of a function.

It feels like a hack but in this case when we're making a wrapper, it makes sense.

**Comment by mottosso** [comment]
The reason they aren't exposed isn't because of dropped globals, but because the module is replacing itself before you gain access to it.

During `import Qt`, Qt.py is read. But once it's done, Qt.py is garbage collected and replaced with whatever we put in `sys.modules`, such as `PySide`.

It's not necessarily a bad idea, but it does make it confusing if we were to add a function or two to the module and expect them to be available like they normally would be.

```python
def reload():
  ...
```

In order for it to be accessible, we would need to attach it to one of the bindings.

```python
def reload():
  ...

PySide.reload = reload
```

Which isn't very obvious I think and might raise questions down the line. Like with `__binding__` which should belong to Qt.py, not a binding itself.

**Comment by fredrikaverpil** [comment]
True, agreed.

So, let's try to avoid setting `sys.modules['Qt']`. What can we do instead?

**Comment by mottosso** [comment]
The only alternative I can think of is more verbose.

```python
import sys
self = sys.modules[__name__]

def load_pyqt5():
  from PyQt5 import QtWidgets, QtCore, QtGui, QtQml, QtQuick
  self.QtWidgets = QtWidgets
  self.QtCore = QtCore
  ...
```

But I'm not sure that's the way to go either, because of the extra mess it creates and because we might miss something, say when Qt goes from 5.6 to 5.7 and gains another submodule. I think there are tens of them already.

**Comment by fredrikaverpil** [comment]
I think that we should leave the heavy lifting to each binding. Then we'd add complimentary data to our module which is beneficial for the user importing our Qt module.

I wouldn't mind having to `import Qt.Wrapper` and then be able to access e.g. `Qt.__binding__`.

What do you think about that?

**Comment by fredrikaverpil** [comment]
Hm, actually, you can't do an `from Qt.Binding import QtWidgets`.

**Comment by fredrikaverpil** [comment]
I believe we should close this issue.

If we ever wish to implement additional functions, there's a high chance they can be called from each binding function (`_pyside2`, `_pyqt5` etc). And if not, we'll deal with it then.

**Comment by mottosso** [comment]
Sure, this isn't a problem anymore.
