### ISSUE TITLE
Repo structure

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt#2]
Right now, the repo acts as a Python module:

```bash
~/code/github
❯ git clone https://github.com/mottosso/Qt.git
Cloning into 'Qt'...
remote: Counting objects: 39, done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 39 (delta 14), reused 28 (delta 3), pack-reused 0
Unpacking objects: 100% (39/39), done.
Checking connectivity... done.

~/code/github
❯ python
Python 2.7.11 (default, Jan 22 2016, 08:29:18)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from Qt import QtGui
Loaded PyQt5
>>>
```

Perhaps there should be a "Qt" folder in the github repo, which will be the Python module. Not sure how this is usually done and how it'll work with PyPi.

**Comment by mottosso** [comment]
Ah, yes. There's no need for the `__init__.py`, just put it in Qt.py.

You'll need to format things a bit differently to make it work with `from Qt import QtWidgets`, but it shouldn't be too tricky.

**Comment by fredrikaverpil** [comment]
Allright!
