### ISSUE TITLE
Override preferred binding

### ISSUE THREAD

**Issue by mottosso** [mottosso/Qt#22]
### Goal

The available Qt bindings - PySide, PySide2, PyQt4 and PyQt5 - are automatically detected. In case two or more bindings are available and one if preferred, currently there is no way of specifying which to pick.

Enable some mechanism with which to specify up-front which bindings to use.

### Motivation

Primarily intended for use in testing, where tests must be able to specify bindings with which to tests against, but could potentially be useful in an enterprise environment where multiple bindings must be present on the `PYTHONPATH`.

### Implementation

Query the value of `QT_PREFERRED_BINDING` and throw an error is this binding doesn't exist.

**Comment by fredrikaverpil** [comment]
Yes, very useful. I've downloaded Qt.py instead of using the pip installed one just because of this.
