### ISSUE TITLE
The growing try/except block; flat is better

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt#9]
Agreed.

This is what we have now:

```python
"""Support Qt 4 and 5, PyQt and PySide"""
try:
    load_pyside2()
except ImportError:
    try:
        load_pyqt5()
    except ImportError:
        try:
            load_pyside()
        except ImportError:
            try:
                load_pyqt4()
            except:
                sys.stderr.write("Qt: Could not find "
                                 "appropriate bindings for Qt\n")
```

**Comment by mottosso** [comment]
I'd like to make it more clear in which order things are imported, that's the main thing. At the moment, it's difficult to tell because it just looks bad.

**Comment by fredrikaverpil** [comment]
I wanted to check whether the __binding__ attribute had been created in order to determine whether the next module should attempt to load or not, but then I noticed that `sys` is of `NoneType`:
https://github.com/mottosso/Qt/issues/15
